### ISSUE TITLE
Contact with multiple phone number

### ISSUE THREAD

**Issue by youtux** [runnersaw/pebble-text#10]
Hello Sawyer, thank you for this great app/tweak!

I am trying it right now, and the first feature that is missing in my opinion is the ability to select the phone number of a contact if there are more than one.
Do you think you can fix that?

Thank you again for the great work!

**Comment by youtux** [comment]
Sorry, I didn't see that you can now use the stock "Send Message" app, never mind.

Beautiful work, again!

**Comment by runnersaw** [comment]
I'm going to go ahead and re-open this, as this is an issue with the TextSender app. However, for now, as a workaround, you can use the "Send Text" app to choose a contact with multiple numbers.

**Comment by runnersaw** [comment]
Closed by #12
