### ISSUE TITLE
Time OS 4.2 issue

### ISSUE THREAD

**Issue by MrL0** [runnersaw/pebble-text#15]
When starting a message via pebbles "send text", a "failed" error is displayed.

Replying to incoming messages or sending new message via textsender is working.

Not sure if this is due to 4.2 itself or textsender.

**Comment by runnersaw** [comment]
Hmm. I recently upgraded to an iPhone 7, which means that I'm not jailbroken, and can't test this out for myself. I'll update this if I'm ever able to test this again.

**Comment by MrL0** [comment]
Would you able to fix the issue if I send you logs and I can test on my end?

If so, please let me know what you need :)

**Comment by joemerlino** [comment]
It's really hard to troubleshoot just with a log, probably they changed some methods he hooks with the tweak. I'll take a look.

**Comment by MrL0** [comment]
Any luck Joe?

**Comment by runnersaw** [comment]
This should be fixed with the 3.0 release on BigBoss. Closing.
