### ISSUE TITLE
Both the TWEAK and the APP crash

### ISSUE THREAD

**Issue by dahauss** [runnersaw/pebble-text#3]
Both the IOS TWEAK and the APP crash with the latest Pebble FIRMWARE and APP when you send the message either a new or a reply.  Please fix....

**Comment by joemerlino** [comment]
It's totally normal since the tweak hooks some methods inside the pebble time app, keep calm and wait the update on a rolled back app.

**Comment by dahauss** [comment]
Rolled Back? is it just the IOS app that needs to be rolled back? I assume you mean to wait for a fix to come out which is being worked on?

**Comment by joemerlino** [comment]
Probably just the iOS app yea. 

You can find the clutched version all around.

**Comment by dahauss** [comment]
Clutched? I would love to find the previous IOS app so I can use the replies until a fix is out for the latest.. any help would be appreciated

**Comment by joemerlino** [comment]
Use the tweak AppAdmin to download the previous version of the app from the appstore or find a clutched (crac*ed) version online.

**Comment by dahauss** [comment]
I tried to use app admin.. Im on IOS 8.4 . I installed the tweak but when you press the OPEN button in the app store it just opens the app and not the download dialog

**Comment by joemerlino** [comment]
You must watch a tutorial on how it works AppAdmin.

**Comment by dahauss** [comment]
i did that and it doesnt work.. what am I doing wrong?

**Comment by runnersaw** [comment]
Fixed this morning. Pebble removed the instance method -(NSString *)rawString; from PBPhoneNumber. Fixed in this pull request: https://github.com/runnersaw/pebble-text/pull/4 and version 1.0.0-278 of tweak.

**Comment by dahauss** [comment]
Thanks for fixing so QUICK!!!!!
